import React, { useEffect, useState } from 'react';

const API = import.meta.env.VITE_API_URL;

function Insights() {
  const [loading, setLoading] = useState(true);
  const [text, setText] = useState('');
  const [error, setError] = useState('');

  useEffect(() => {
    loadSuggestions();
  }, []);

  const loadSuggestions = async () => {
    try {
      setLoading(true);
      setError('');

      const res = await fetch(`${API}/api/suggest?user_id=demo_user`);
      const data = await res.json();

      const suggestions =
        data?.suggestions ||
        data?.data?.suggestions ||
        '';

      if (typeof suggestions === 'string') {
        setText(suggestions);
      } else if (Array.isArray(suggestions)) {
        setText(suggestions.join('\n'));
      } else {
        setText('');
      }
    } catch (err) {
      setError('Unable to load suggestions.');
      setText('');
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="relative z-10 pt-24 md:pt-32 pb-32 md:pb-24 px-4 md:px-10 max-w-4xl mx-auto flex flex-col gap-8">
      <div className="flex flex-col gap-2 text-center items-center">
        <h1 className="font-headline-xl text-3xl md:text-5xl font-bold text-on-surface">
          Smart Suggestions
        </h1>

        <p className="font-body-md text-on-surface-variant max-w-lg">
          Actionable, highly contextual alerts generated by your Autonomous Financial Twin.
        </p>
      </div>

      {loading && (
        <div className="p-6 bg-surface-container-high border border-white/10 rounded-sm">
          <p className="font-body-sm text-on-surface-variant">
            Loading Gemini suggestions...
          </p>
        </div>
      )}

      {error && (
        <div className="p-6 bg-surface-container-high border border-red-500/30 rounded-sm">
          <p className="font-body-sm text-on-surface-variant">{error}</p>
        </div>
      )}

      {!loading && (
        <>
          <div className="flex flex-col gap-4 mt-8">
            <div className="p-6 bg-surface-container-highest border-l-2 border-primary rounded-r-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <span className="material-symbols-outlined text-primary text-sm">
                  stars
                </span>

                <span className="font-label-lg text-primary text-xs uppercase tracking-widest">
                  Overall Assessment
                </span>
              </div>

              <p className="font-body-sm text-on-surface-variant whitespace-pre-line">
                {text || 'Suggestions loaded successfully.'}
              </p>
            </div>
          </div>

          <div className="p-6 bg-surface-container-high border-l-2 border-secondary rounded-r-sm flex flex-col gap-2">
            <div className="flex items-center gap-2">
              <span className="material-symbols-outlined text-secondary text-sm">
                trending_up
              </span>

              <span className="font-label-lg text-secondary text-xs uppercase tracking-widest">
                Top 3 Saving Opportunities
              </span>
            </div>

            <p className="font-body-sm text-on-surface-variant">
              AI-generated recommendations based on your spending behaviour,
              forecast trends, savings rate and risk profile.
            </p>
          </div>

          <div className="flex flex-col gap-4 mt-8">
            <div className="p-6 bg-surface-container-highest border-l-2 border-primary rounded-r-sm flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <span className="material-symbols-outlined text-primary text-sm">
                  stars
                </span>

                <span className="font-label-lg text-primary text-xs uppercase tracking-widest">
                  Category-Specific Tips
                </span>
              </div>

              <p className="font-body-sm text-on-surface-variant">
                Smart category guidance generated dynamically from uploaded
                transaction behaviour.
              </p>
            </div>
          </div>

          <div className="p-6 bg-surface-container-high border-l-2 border-secondary rounded-r-sm flex flex-col gap-2">
            <div className="flex items-center gap-2">
              <span className="material-symbols-outlined text-secondary text-sm">
                trending_up
              </span>

              <span className="font-label-lg text-secondary text-xs uppercase tracking-widest">
                Next Month Action Plan
              </span>
            </div>

            <p className="font-body-sm text-on-surface-variant">
              Maintain discipline, reduce leakage, and improve monthly savings
              using forecast-backed actions.
            </p>

            <h3 className="font-headline-md text-xl text-on-surface">
              Positive Reinforcement
            </h3>

            <p className="font-body-sm text-on-surface-variant">
              You are already taking meaningful steps toward stronger financial
              health.
            </p>
          </div>
        </>
      )}
    </main>
  );
}

export default Insights;
