import React, { useEffect, useState } from "react";

const API =
  import.meta.env.VITE_API_URL || "https://aft-1-6zfr.onrender.com";

function Insights() {
  const [data, setData] = useState(null);

  useEffect(() => {
    fetch(`${API}/api/suggest?user_id=demo_user`)
      .then((res) => res.json())
      .then((result) => setData(result))
      .catch((err) => console.log(err));
  }, []);

  const suggestions = data?.suggestions || [];

  return (
    <main className="relative z-10 pt-24 md:pt-32 pb-32 md:pb-24 px-4 md:px-10 max-w-4xl mx-auto flex flex-col gap-8">

      <div className="flex flex-col gap-2 text-center items-center">
        <h1 className="font-headline-xl text-3xl md:text-5xl font-bold text-on-surface">
          Smart Suggestions
        </h1>

        <p className="font-body-md text-on-surface-variant max-w-lg">
          Actionable, highly contextual alerts generated by your Autonomous Financial Twin.
        </p>
      </div>

      <div className="flex flex-col gap-4 mt-8">

        {suggestions.length > 0 ? (
          suggestions.map((item, index) => (
            <div
              key={index}
              className="p-6 bg-surface-container-highest border-l-2 border-primary rounded-r-sm flex flex-col gap-2"
            >
              <div className="flex items-center gap-2">
                <span className="material-symbols-outlined text-primary text-sm">
                  stars
                </span>

                <span className="font-label-lg text-primary text-xs uppercase tracking-widest">
                  AI Suggestion {index + 1}
                </span>
              </div>

              <p className="font-headline-md text-lg text-on-surface">
                {item}
              </p>
            </div>
          ))
        ) : (
          <div className="text-center text-on-surface-variant">
            Loading Suggestions...
          </div>
        )}

      </div>

    </main>
  );
}

export default Insights;
