import React, { useEffect, useState } from 'react';

const API = import.meta.env.VITE_API_URL;

function Insights() {
  return (
    <main className="relative z-10 pt-24 md:pt-32 pb-32 md:pb-24 px-4 md:px-10 max-w-4xl mx-auto flex flex-col gap-8">
      <div className="flex flex-col gap-2 text-center items-center">
        <h1 className="font-headline-xl text-3xl md:text-5xl font-bold text-on-surface">Smart Suggestions</h1>
        <p className="font-body-md text-on-surface-variant max-w-lg">
          Actionable, highly contextual alerts generated by your Autonomous Financial Twin.
        </p>
      </div>

      <div className="flex flex-col gap-4 mt-8">
        <div className="p-6 bg-surface-container-highest border-l-2 border-primary rounded-r-sm flex flex-col gap-2">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-primary text-sm">stars</span>
            <span className="font-label-lg text-primary text-xs uppercase tracking-widest">Overall Assessment</span>
          </div>
          <p className="font-body-sm text-on-surface-variant">Your spending is stable in the sense that rent is predictable every month, but your overall savings rate looks modest because discretionary expenses regularly stack up on top of fixed costs. The biggest concern is not one-off overspending — it’s the repeated pull from shopping, food delivery, travel, and short-term lifestyle costs, which makes your month-end cash flow tighter than it needs to be.</p>
        </div>
      


      <div className="p-6 bg-surface-container-high border-l-2 border-secondary rounded-r-sm flex flex-col gap-2">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-secondary text-sm">trending_up</span>
            <span className="font-label-lg text-secondary text-xs uppercase tracking-widest">Top 3 Saving Opportunities</span>
          </div>
            <p className="font-body-sm text-on-surface-variant"><b>Cut shopping spikes in half.</b> Your shopping spend is one of the largest non-rent categories, and the biggest wins come from months with sale-driven or impulse buys like Amazon, Myntra, and Flipkart. A realistic target is ₹2,500–₹4,000/month saved by delaying non-essential purchases by 48 hours and capping sale-day spending.</p>
            <p className="font-body-sm text-on-surface-variant"><b>Reduce food delivery frequency.</b> Food & Dining shows repeated Swiggy and Zomato usage, with a clear spike in higher-spend months. Switching just 3–4 orders per month to home-cooked meals can save about ₹1,200–₹2,000/month.</p>
            <p className="font-body-sm text-on-surface-variant"><b>Control travel and cab leakage.</b> Transportation and Travel both appear meaningfully in the data, especially cab rides, flight bookings, and short-stay travel costs. Replacing a few cab trips with public transport or planning travel earlier could save ₹1,000–₹2,500/month on average.</p>
      

      <div className="flex flex-col gap-4 mt-8">
        <div className="p-6 bg-surface-container-highest border-l-2 border-primary rounded-r-sm flex flex-col gap-2">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-primary text-sm">stars</span>
            <span className="font-label-lg text-primary text-xs uppercase tracking-widest">Category-Specific Tips</span>
          </div>
          <h3 className="font-headline-md text-xl text-on-surface">Shopping</h3>
          <p className="font-body-sm text-on-surface-variant">Create a 72-hour rule for all non-essential purchases above ₹1,500, because your data shows that shopping is a recurring high-value category rather than a rare exception. Also, split shopping into “need now” and “wait till next month” buckets so sale events don’t automatically become spending events.</p>
          <h3 className="font-headline-md text-xl text-on-surface">Food & Dining</h3>
          <p className="font-body-sm text-on-surface-variant">Set a weekly delivery cap instead of a monthly one, because the spending spikes are more visible when food orders cluster in a few weeks. You could also reserve one or two fixed “eat out” days and keep the rest of the week meal-prep based.</p>
        
        </div>

        <div className="p-6 bg-surface-container-high border-l-2 border-secondary rounded-r-sm flex flex-col gap-2">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-secondary text-sm">trending_up</span>
            <span className="font-label-lg text-secondary text-xs uppercase tracking-widest">Next Month Action Plan</span>
          </div>
            <p className="font-body-sm text-on-surface-variant">Keep total discretionary spending below your forecast band by setting a hard ceiling on shopping and restaurant expenses.</p>
            <p className="font-body-sm text-on-surface-variant">Limit food delivery to a fixed number of orders per week and track whether the total stays below this month’s trend.</p>
            <p className="font-body-sm text-on-surface-variant">Move at least one cab ride or impulse purchase each week into a “skip or delay” decision so you build savings without feeling restricted.</p>
      
        
          <h3 className="font-headline-md text-xl text-on-surface">Positive Reinforcement</h3>
          <p className="font-body-sm text-on-surface-variant">You are consistently paying rent and handling recurring essentials on time, which shows strong baseline financial discipline. You also do have at least one healthy habit in the mix — your SIP mutual fund contribution indicates that you are already thinking beyond short-term spending.</p>
        </div>
      </div>
    </main>
  );
}

export default Insights;
